export const PERMISSIONS = {
  ADMIN_ACCESS: 'admin:access',
  USER_READ: 'user:read',
  USER_WRITE: 'user:write',
  USER_DELETE: 'user:delete',
  SUBSCRIPTION_READ: 'subscription:read',
  SUBSCRIPTION_WRITE: 'subscription:write',
  SUBSCRIPTION_DELETE: 'subscription:delete',
  PERMISSION_READ: 'permission:read',
  PERMISSION_WRITE: 'permission:write',
  LOG_READ: 'log:read',
  ANALYTICS_READ: 'analytics:read',
  SYSTEM_CONFIG: 'system:config',
} as const

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS]

export const PERMISSION_GROUPS = {
  USER_MANAGEMENT: [PERMISSIONS.USER_READ, PERMISSIONS.USER_WRITE, PERMISSIONS.USER_DELETE],
  SUBSCRIPTION_MANAGEMENT: [PERMISSIONS.SUBSCRIPTION_READ, PERMISSIONS.SUBSCRIPTION_WRITE, PERMISSIONS.SUBSCRIPTION_DELETE],
  PERMISSION_MANAGEMENT: [PERMISSIONS.PERMISSION_READ, PERMISSIONS.PERMISSION_WRITE],
  SYSTEM_MANAGEMENT: [PERMISSIONS.LOG_READ, PERMISSIONS.ANALYTICS_READ, PERMISSIONS.SYSTEM_CONFIG],
} as const 